apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-website-prod
  labels:
    app: frontend-website-prod
spec:
  replicas: 1
  minReadySeconds: 30
  selector:
    matchLabels:
      app: frontend-website-prod
  template:
    metadata:
      labels:
        app: frontend-website-prod
    spec:
      containers:
      - name: frontend-website-prod
        image: "{{ .Values.image.registry }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        ports:
        - containerPort: 5173
      resources:
        limits:
          cpu: "1"
          memory: "1Gi"
        requests:
          cpu: "0.5"
          memory: "0.5Gi"
